### PR TITLE
Add zstd to "On compress"

### PR DESCRIPTION
**Pull request by jodavies**
To compile I needed to fetch the wrapper submodule manually, is this intended?

### CODE REVIEW

**Comment by tueda** [comment]
I think it is not good to always run `git submodule update --init` in `configure.ac` or `Makefile.am` because it reverts temporal changes in submodules, but we can do it if `zstd_zlibwrapper.h` doesn't exist (i.e., nothing in the submodule is cloned).

**Comment by tueda** [comment]
Would it be okay to squash these commits as in https://github.com/tueda/form/commits/feat-zstd-3?

**Comment by jodavies** [comment]
Yes this looks fine.

**Comment by tueda** [comment]
Then, I will create a PR for the upstream.

**Pull request closed without merging**
